### ISSUE TITLE
Countdown text formatting

### ISSUE THREAD

**Issue by raihanmaziz** [raihanmaziz/Muhammad-Raihan-Aziz---Tugas-2#4]
Countdown text tidak hilang ketika selesai countdown

**Comment by raihanmaziz** [comment]
Menambah line "CountdownText.OnCountdownFinish += OnCountdownFinish" pada void OnEnable() dalam GameManager.cs
Sekaligus menghilangkan tanda ! pada line "public bool GameOver { get { return !gameOver; } }" agar state play tidak terbalik dengan state game over.

**Comment by agunggm** [comment]
Bisa dipecah lagi ya issue nya ini, karna title nya text formatting maka issue yang dikerjakan seputaran hal tersebut, jika menemukan issue terkait bisa dibuatkan issue terpecah agar tidak tercampur
